In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame({'Math_Marks':[94,80,70,58,50],
                 'Physics_Marks':[85,75,67,49,45],
                 'Attendance':[95,84,75,60,55],
})

In [3]:
df

,Math_Marks,Physics_Marks,Attendance
0,94,85,95
1,80,75,84
2,70,67,75
3,58,49,60
4,50,45,55


In [4]:
parameters={'w1':np.random.randn(2, 2) * 0.01,
            'b1':np.zeros((2, 1)),
            'w2':np.random.randn(2, 1) * 0.01,
            'b2':np.zeros((1, 1))
            }
parameters

{'w1': array([[ 0.01370095, -0.02860699],
        [ 0.01348323, -0.01110746]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.00689902],
        [0.0032062 ]]),
 'b2': array([[0.]])}

In [5]:
vals=df.to_numpy()
vals

array([[94, 85, 95],
       [80, 75, 84],
       [70, 67, 75],
       [58, 49, 60],
       [50, 45, 55]])

In [6]:
A=np.delete(vals, 2, axis=1)
A


array([[94, 85],
       [80, 75],
       [70, 67],
       [58, 49],
       [50, 45]])

In [7]:
def forward_to_layer(A, parameters):
    Z1 = np.dot(A, parameters['w1']) + parameters['b1'].T
    A_new = 1/(1+np.exp(-Z1))
    return A_new

A_layer = forward_to_layer(A, parameters)
A_layer

array([[0.91938081, 0.02575106],
       [0.89161243, 0.04222426],
       [0.86558142, 0.06027391],
       [0.81081787, 0.09943923],
       [0.78445048, 0.12673008]])

In [18]:
A.shape

(5, 2)

In [19]:
parameters['w1'].shape

(2, 2)

In [8]:
def forward_to_output(A_new, parameters):
    Z2 = np.dot(A_new, parameters['w2']) + parameters['b2'].T
    A_output = 1/(1+np.exp(-Z2))
    return A_output

A_output=forward_to_output(A_layer, parameters)
A_output

array([[0.50160634],
       [0.50157165],
       [0.50154122],
       [0.50147816],
       [0.50145456]])

In [9]:
vals[:,2:3]

array([[95],
       [84],
       [75],
       [60],
       [55]])

In [10]:
test=np.ones((A.shape[0], 1)).T
test

array([[1., 1., 1., 1., 1.]])

In [20]:
def backward_pass(A, A_layer, A_output, y, parameters, learning_rate):
    dA_output = A_output - y

    dw1 = np.dot(A.T, dA_layer)
    dw2 = np.dot(A_layer.T, dA_output)

    db2 = np.dot(np.ones((1, A.shape[0])), dA_output)
    db1 = np.dot(np.ones((1, A.shape[0])), dA_layer)

    dA_layer = np.dot(dA_output, parameters['w2'].T)

    parameters['w1'] = parameters['w1'] - learning_rate * dw1
    parameters['b1'] = parameters['b1'] - learning_rate * db1
    parameters['w2'] = parameters['w2'] - learning_rate * dw2
    parameters['b2'] = parameters['b2'] - learning_rate * db2

    return parameters

y = vals[:, 2:3]
y_min, y_max = y.min(), y.max()
y = (y - y_min) / (y_max - y_min)

A = np.delete(vals, 2, axis=1)
A_min, A_max = A.min(axis=0), A.max(axis=0)
A = (A - A_min) / (A_max - A_min)


In [12]:
A.shape

(5, 2)

In [13]:
parameters

{'w1': array([[ 0.01370095, -0.02860699],
        [ 0.01348323, -0.01110746]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.00689902],
        [0.0032062 ]]),
 'b2': array([[0.]])}

In [14]:
parameters['w1'].shape

(2, 2)

In [15]:
def error(y, A_output):
    return np.mean((y - A_output)**2)


In [17]:
epochs=2000
for i in range(epochs):
    A_x=forward_to_layer(A, parameters)
    A_output=forward_to_output(A_x, parameters)
    parameters=backward_pass(A, A_x, A_output, y, parameters, 0.1)
    err = error(y, A_output)
    if (i+1) % 100 == 0:
        print(f"Epoch {i+1}, Error: {err:.6f}")
parameters

ValueError: operands could not be broadcast together with shapes (5,2) (2,2) 

In [ ]:
def test(Maths, Physics):
    input_data = np.array([[Maths, Physics]])
    input_data = (input_data - A_min) / (A_max - A_min)
    A_new=forward_to_layer(input_data, parameters)
    A_output=forward_to_output(A_new, parameters)
    predicted_attendance = A_output * (y_max - y_min) + y_min
    print("Predicted Attendance:")
    print(predicted_attendance)
test(85, 90)

Predicted Attendance:
[[88.92559955]]
